# Generated by Django 3.2.16 on 2023-04-23 12:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmarkjob',
            options={'verbose_name': 'Bookmark Job', 'verbose_name_plural': 'Bookmark Jobs'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoory', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='./static/images/hero_1.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Branch Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(max_length=300, verbose_name='Branch Name'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'Closed'), ('3', 'Coming Soon')], max_length=1, verbose_name='Shop Type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateField(verbose_name='Auto Close Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=30, verbose_name='Avg Spend'),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(verbose_name='Website'),
        ),
    ]
