# Generated by Django 3.2.16 on 2023-04-23 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0002_auto_20230423_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
    ]
