# Generated by Django 3.2.16 on 2023-04-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0003_remove_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Branch Name'),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(verbose_name='Logo'),
        ),
    ]
