# Generated by Django 3.2.16 on 2023-04-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0004_auto_20230423_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
